import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import Sidebarmenu from './Sidebarmenu/page';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen bg-gray-900 text-gray-100">

      <Link href="/startseite">
        
      </Link>
    
        <main className="flex-1 p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
