import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen bg-gray-900 text-gray-100">
        <aside className="w-64 bg-gray-800 p-6">
          <nav className="space-y-4">
            <Link href='schuelerDaten'className="block text-lg font-medium hover:text-blue-400 transition"> Schüler Daten </Link>
            <Link href='uebungsfahrt'className="block text-lg font-medium hover:text-blue-400 transition" >Übungsfahrt </Link>
            <Link href='sonderfahrt' className="block text-lg font-medium hover:text-blue-400 transition"> Sonderfahrt</Link>
            <Link href='vorpruefund' className="block text-lg font-medium hover:text-blue-400 transition"> Vorprüfung</Link>
          </nav>
        </aside>
        <main className="flex-1 p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
